ChatApp/ViewComponents/RoomViewComponent.cs
using ChatApp.Database;
using ChatApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace ChatApp.ViewComponents
{
    public class RoomViewComponent: ViewComponent
    {
        private AppDbContext _ctx;

        public RoomViewComponent(AppDbContext ctx)
        {
            _ctx = ctx;
        }

        public IViewComponentResult Invoke()
        {
            var userId = HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var chats = _ctx.ChatUsers
                .Include(x => x.Chat)
                .Where(x => x.UserId == userId && x.Chat.Type == ChatType.Room)
                .Select(x => x.Chat)
                .ToList();
            return View(chats);
        }
    }
}

ChatApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<User> SignInManager;
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ChatApp</title>

    <link href="~/css/site.css" rel="stylesheet" />

</head>
<body>
    <div class=navbar>

        @if (SignInManager.IsSignedIn(User))
        {
            <a asp-controller="Home" asp-action="Index">Home</a>
            <a asp-controller="Home" asp-action="Find">Find</a>
            <a asp-controller="Home" asp-action="Private">Private</a>

           

            
            List<SelectListItem> listItems = new List<SelectListItem>();
            listItems.Add(new SelectListItem
            {
                Text = "english",
                Value = "en"
            });
            listItems.Add(new SelectListItem
            {
                Text = "swedish",
                Value = "sv",
                Selected = true
            });


    <div style="align-self:center">
        &nbsp;&nbsp;
        @Html.DropDownList("langs", listItems)
    </div>
    <div class=navbar>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <a asp-controller="Account" asp-action="Logout">Logout @User.Identity.Name</a>
    </div>
            
        }



        @*@Html.DropDownList("SLanguage",
        new SelectList(Enum.GetValues(typeof(Transslate.Language)), Enum.GetValues(typeof(Transslate.Language)).ToString(), Enum.GetValues(typeof(Transslate.LanguageText)).ToString(), "Select Language"));*@
        @*@{
            List<SelectListItem> listItems = new List<SelectListItem>();
            listItems.Add(new SelectListItem
            {
                Text = "english",
                Value = "en"
            });
            listItems.Add(new SelectListItem
            {
                Text = "swedish",
                Value = "sv",
                Selected = true
            });
        }

        @Html.DropDownList("langs", listItems)*@



    </div>
    <div class="main">
        @if (User.Identity.IsAuthenticated)
        {
            <vc:room></vc:room>
        }

        <div class="chat">
            @RenderBody()
        </div>
    </div>
    <div class="modal" id="create-room-modal">
        <form asp-controller="Home" asp-action="CreateRoom" class="modal-body">
            <button type="button" class="close" onclick="closeModal()">x</button>
            <header>Create Room</header>
            <div>
                <input name="name">
            </div>
            <footer>
                <button>Create</button>
            </footer>
        </form>
    </div>
    <script src="~/js/site.js"></script>
    @RenderSection("Scripts", false)
</body>
</html>